eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 8002
spring:
  application:
    name: epa-gateway
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
zuul:
  routes:
    order-service:
      path: /api/order-service/**
      serviceId: order-service
    user-service:
      path: /api/user-service/**
      serviceId: user-service
#security:
#  oauth2:
#    client:
#      access-token-uri: http://localhost:8005/oauth/token
#      user-authorization-uri: http://localhost:8005/oauth/authorize
#      client-id: app
#    resource:
#      user-info-uri: http://localhost:8005/user
#      prefer-token-info: false



